# Generated by Django 4.1.7 on 2023-02-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='name',
            new_name='band_name',
        ),
    ]
