# Generated by Django 4.1.7 on 2023-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0003_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='date_formed',
        ),
        migrations.AlterField(
            model_name='band',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
