# Generated by Django 4.1.7 on 2023-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0004_remove_band_date_formed_alter_band_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
