# Generated by Django 4.1.7 on 2023-02-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0006_alter_band_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
