# Generated by Django 4.1.7 on 2023-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0009_remove_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True),
        ),
    ]
