# Generated by Django 4.1.7 on 2023-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0011_alter_venue_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistListedGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('venue_location', models.CharField(choices=[('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland')], max_length=100)),
                ('venue_name', models.CharField(max_length=100)),
                ('genre_of_gig', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True)),
            ],
        ),
    ]
