# Generated by Django 4.1.7 on 2023-04-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0012_artistlistedgig'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='date_of_gig',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artistlistedgig',
            name='payment',
            field=models.IntegerField(null=True),
        ),
    ]
