# Generated by Django 4.1.7 on 2023-04-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0013_artistlistedgig_date_of_gig_artistlistedgig_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistlistedgig',
            old_name='venue_location',
            new_name='country_of_venue',
        ),
    ]
