# Generated by Django 4.1.7 on 2023-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0014_rename_venue_location_artistlistedgig_country_of_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistlistedgig',
            name='date_of_gig',
        ),
    ]
