# Generated by Django 4.1.7 on 2023-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0015_remove_artistlistedgig_date_of_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='date_of_gig',
            field=models.DateField(null=True),
        ),
    ]
