# Generated by Django 4.1.7 on 2023-04-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0017_band_country_band_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='type_of_music',
            field=models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
