# Generated by Django 4.1.7 on 2023-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0019_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bio',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
