# Generated by Django 4.1.7 on 2023-05-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0025_alter_artist_county_alter_artist_gigging_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='type_of_artist',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo'), ('Any', 'Any')], max_length=50, null=True),
        ),
    ]
