# Generated by Django 4.1.7 on 2023-05-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0027_alter_artist_gigging_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='gig_mania_backend.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
