# Generated by Django 4.1.7 on 2023-05-13 13:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0028_unavailability_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='summary',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gigging_distance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('England', (('South East', 'South East'), ('South West', 'South West'), ('London', 'London'), ('East of England', 'East of England'), ('West Midlands', 'West Midlands'), ('East Midlands', 'East Midlands'), ('Yorkshire and the Humber', 'Yorkshire and the Humber'), ('North West', 'North West'), ('North East', 'North East'))), ('Scotland', (('Highlands and Islands', 'Highlands and Islands'), ('North East Scotland', 'North East Scotland'), ('Central Belt', 'Central Belt'), ('South West Scotland', 'South West Scotland'))), ('Wales', (('North Wales', 'North Wales'), ('Mid Wales', 'Mid Wales'), ('South West Wales', 'South West Wales'), ('South East Wales', 'South East Wales'))), ('Northern Ireland', (('Antrim Coast and Glens', 'Antrim Coast and Glens'), ('Belfast', 'Belfast'), ('The Causeway Coast', 'The Causeway Coast'), ('County Armagh', 'County Armagh'), ('County Down', 'County Down'), ('Fermanagh Lakelands', 'Fermanagh Lakelands'), ('Lough Neagh', 'Lough Neagh'), ('Sperrin Mountains', 'Sperrin Mountains'), ('The Mournes', 'The Mournes'))), ('All Regions', (('Nationwide', 'Nationwide'),))], max_length=200),
        ),
    ]
