# Generated by Django 4.1.7 on 2023-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0031_artist_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.AlterField(
            model_name='artist',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
