# Generated by Django 4.1.7 on 2023-05-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0032_remove_artist_bio_alter_artist_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='summary',
            new_name='bio',
        ),
    ]
