# Generated by Django 4.1.7 on 2023-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0034_artist_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='artist_images/'),
        ),
    ]
