# Generated by Django 4.1.7 on 2023-06-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0040_venue_image_alter_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
