# Generated by Django 4.1.7 on 2023-06-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0041_artist_facebook_artist_twitter_artist_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='username',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='username',
        ),
    ]
