# Generated by Django 4.1.7 on 2023-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0042_remove_artist_username_remove_venue_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type_of_artist',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True),
        ),
    ]
