# Generated by Django 4.1.7 on 2023-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0043_alter_artist_type_of_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
