# Generated by Django 4.1.7 on 2023-06-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0046_venue_bio_venue_country_venue_county_venue_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='type_of_music',
            new_name='type_of_act',
        ),
    ]
