# Generated by Django 4.1.7 on 2023-06-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0048_artistlistedgig_type_of_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistlistedgig',
            name='type_of_gig',
            field=models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=50, null=True),
        ),
    ]
