# Generated by Django 4.1.7 on 2023-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0049_alter_artistlistedgig_type_of_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pro_member',
            field=models.BooleanField(default=False),
        ),
    ]
