# Generated by Django 4.1.7 on 2023-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0050_artist_pro_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='pro_member',
        ),
        migrations.AddField(
            model_name='artist',
            name='membership_type',
            field=models.IntegerField(null=True),
        ),
    ]
