# Generated by Django 4.1.7 on 2023-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0051_remove_artist_pro_member_artist_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Signup Date'),
        ),
    ]
