# Generated by Django 4.1.7 on 2023-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0052_artist_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Signup Date'),
        ),
    ]
