# Generated by Django 4.1.7 on 2023-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0056_alter_venue_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='signup_date',
            field=models.DateTimeField(null=True, verbose_name='Signup Date'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='signup_date',
            field=models.DateTimeField(null=True, verbose_name='Signup Date'),
        ),
    ]
