# Generated by Django 4.1.7 on 2023-06-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0058_alter_artist_signup_date_alter_venue_signup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='signup_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='signup_date',
        ),
    ]
