# Generated by Django 4.1.7 on 2023-06-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0059_remove_artist_signup_date_remove_venue_signup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='membership_type',
            new_name='artist_membership_type',
        ),
    ]
