# Generated by Django 4.1.7 on 2023-06-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0060_rename_membership_type_artist_artist_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_membership_type',
            field=models.IntegerField(null=True),
        ),
    ]
