# Generated by Django 4.1.7 on 2023-06-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0063_membershipoptions_type_of_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipoptions',
            name='cost_frequency',
        ),
        migrations.AddField(
            model_name='membershipoptions',
            name='disclosure',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membershipoptions',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
