# Generated by Django 4.1.7 on 2023-06-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0065_gig_gigapplication_delete_artistlistedgig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='artist_type',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=100, null=True),
        ),
    ]
