# Generated by Django 4.1.7 on 2023-06-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0066_gig_artist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='genre_of_gig',
            new_name='genre',
        ),
    ]
