# Generated by Django 4.1.7 on 2023-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0067_rename_genre_of_gig_gig_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='advertiser_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('venue', 'Venue')], default='artist', max_length=10),
        ),
    ]
