# Generated by Django 4.1.7 on 2023-06-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0068_gig_advertiser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='advertiser_type',
        ),
    ]
