# Generated by Django 4.1.7 on 2023-06-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0071_alter_gig_artist_type_alter_gig_country_of_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='artist_type',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='country_of_venue',
            field=models.CharField(choices=[('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gig',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Blues', 'Blues'), ('World Music', 'World Music')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='type_of_gig',
            field=models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=50, null=True),
        ),
    ]
