# Generated by Django 4.1.7 on 2023-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0074_venuelistedgig'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='artist_type',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True),
        ),
    ]
