# Generated by Django 4.1.7 on 2023-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0075_artistlistedgig_artist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='user_type',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Venue', 'Venue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venuelistedgig',
            name='user_type',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Venue', 'Venue')], max_length=50, null=True),
        ),
    ]
