# Generated by Django 4.1.7 on 2023-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0076_artistlistedgig_user_type_venuelistedgig_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistWrittenReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_performance', models.DateField(null=True)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
    ]
