# Generated by Django 4.1.7 on 2023-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0077_artistwrittenreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistwrittenreview',
            name='artist_name',
            field=models.TextField(max_length=100),
        ),
    ]
