# Generated by Django 4.1.7 on 2023-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0078_alter_artistwrittenreview_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistwrittenreview',
            name='artist_review',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='artistwrittenreview',
            name='artist_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
