# Generated by Django 4.1.7 on 2023-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0080_venuewrittenreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuewrittenreview',
            old_name='artist_review',
            new_name='review',
        ),
        migrations.AddField(
            model_name='venuewrittenreview',
            name='venue_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
