# Generated by Django 4.1.7 on 2023-06-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0081_rename_artist_review_venuewrittenreview_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistwrittenreview',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venuewrittenreview',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
