# Generated by Django 4.1.7 on 2023-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0082_artistwrittenreview_rating_venuewrittenreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistwrittenreview',
            name='is_approved',
            field=models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venuewrittenreview',
            name='is_approved',
            field=models.CharField(choices=[('Original Music', 'Original Music'), ('Covers', 'Covers'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
