# Generated by Django 4.1.7 on 2023-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0083_artistwrittenreview_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistwrittenreview',
            name='is_approved',
            field=models.CharField(choices=[('Under review', 'Under review'), ('Unapproved', 'Unapproved'), ('Approved', 'Approved')], default='Under review', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuewrittenreview',
            name='is_approved',
            field=models.CharField(choices=[('Under review', 'Under review'), ('Unapproved', 'Unapproved'), ('Approved', 'Approved')], default='Under review', max_length=100, null=True),
        ),
    ]
