# Generated by Django 4.1.7 on 2023-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0084_alter_artistwrittenreview_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuelistedgig',
            name='artist_type',
            field=models.CharField(choices=[('Full band', 'Full band'), ('Solo artist', 'Solo artist'), ('Duo', 'Duo')], max_length=50, null=True),
        ),
    ]
