# Generated by Django 4.1.7 on 2023-07-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0086_gigapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuelistedgig',
            name='venue_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig_mania_backend.venue'),
        ),
    ]
