# Generated by Django 4.1.7 on 2023-07-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0087_alter_venuelistedgig_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuelistedgig',
            old_name='venue_name',
            new_name='venue',
        ),
    ]
