# Generated by Django 4.1.7 on 2023-07-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0088_rename_venue_name_venuelistedgig_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuelistedgig',
            name='venue',
        ),
        migrations.AddField(
            model_name='venuelistedgig',
            name='venue_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
