# Generated by Django 4.1.7 on 2023-07-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0089_remove_venuelistedgig_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuelistedgig',
            name='country_of_venue',
            field=models.CharField(choices=[('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern Ireland', 'Northern Ireland')], max_length=100, null=True),
        ),
    ]
