# Generated by Django 4.1.7 on 2023-07-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0092_alter_artistlistedgig_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistlistedgig',
            name='artist_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuelistedgig',
            name='venue_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
