# Generated by Django 4.1.7 on 2023-07-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0093_alter_artistlistedgig_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistlistedgig',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='venuelistedgig',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='artistlistedgig',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_listed_gigs', to='gig_mania_backend.artist'),
        ),
        migrations.AddField(
            model_name='venuelistedgig',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_listed_gigs', to='gig_mania_backend.venue'),
        ),
    ]
