# Generated by Django 4.1.7 on 2023-07-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0095_artist_user_type_venue_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistlistedgig',
            old_name='artist_type',
            new_name='type_of_artist',
        ),
    ]
