# Generated by Django 4.1.7 on 2023-08-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0097_gigapplication_date_of_gig_gigapplication_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
