# Generated by Django 4.1.7 on 2023-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0099_remove_gigapplication_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigapplication',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
