# Generated by Django 4.1.7 on 2023-09-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0101_remove_gigapplication_date_of_gig_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GigApplication',
            new_name='ArtistGigApplication',
        ),
        migrations.CreateModel(
            name='VenueGigApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gig_mania_backend.artist')),
                ('venue_gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gig_mania_backend.venuelistedgig')),
            ],
        ),
    ]
