# Generated by Django 4.1.7 on 2023-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0102_rename_gigapplication_artistgigapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlistedgig',
            name='num_applications',
            field=models.IntegerField(null=True),
        ),
    ]
