# Generated by Django 4.1.7 on 2023-09-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0105_venuelistedgig_num_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuegigapplication',
            name='venue_gig',
        ),
        migrations.AddField(
            model_name='venuegigapplication',
            name='artist_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gig_mania_backend.artistlistedgig'),
        ),
    ]
