# Generated by Django 4.1.7 on 2023-10-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig_mania_backend', '0107_remove_venuegigapplication_artist_gig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='reason',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='status',
            field=models.CharField(default='Unavailable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artistgigapplication',
            name='artist_gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='gig_mania_backend.artistlistedgig'),
        ),
    ]
